name: Docker Build

on:
  push:
    branches:
      - master 
      - docker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t groundgan -f docker/Dockerfile .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_UNAME }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Push Docker image
      run: docker push groundgan
